# Generated by Django 6.0.5 on 2026-05-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='An-Nadaa Diagnostic Centre', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text="Short motto, e.g. 'Your Health, Our Priority'", max_length=300)),
                ('address', models.TextField(help_text='Full address printed on reports')),
                ('phone', models.CharField(help_text='Phone number(s) — use commas for multiple', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, help_text='Logo printed at the top of every report', null=True, upload_to='centre/')),
            ],
            options={
                'verbose_name': 'Centre Profile',
                'verbose_name_plural': 'Centre Profile',
            },
        ),
    ]
