# Generated by Django 6.0.5 on 2026-05-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doctor_notes',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
        migrations.AddField(
            model_name='report',
            name='signatory',
            field=models.CharField(blank=True, default='', help_text='Name and qualifications of the result signatory, e.g. Dr. Aminu Musa, MBBS, FWACP', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Parameter values entered by the lab technician'),
        ),
    ]
